name: facial_stadium
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  local_auth: ^2.1.6
  google_fonts: ^4.0.4
  
  splash_screen_view: ^3.0.0
  firebase_storage: ^11.6.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  image_picker: ^1.0.2
  shared_preferences: ^2.1.2
  flutter_svg: ^1.0.3
  get: ^4.6.5
  intl_phone_field: ^3.2.0
  fluttertoast: ^8.2.5
  google_mlkit_face_detection: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/icons/



